export const embroideryInfo = [
    {
      id: 1,
      image: '4x4WitchHat.jpg',
      designer: 'Julias Needle Designs',
      item: 'hat',
      hoopSize: ['4x4','5x7'],
      metaTags: ['hat','halloween','witch'], 
      holiday: 'halloween',
      category: '',
      season: 'fall',
      colectionName: '',
      single: true,
      alphabet: false,
      applique: false,
      zipFile: 'FREE4x4WitchHat'
    },
    {
      id: 2,
      image: '6x10FlourishMonths-September.jpg',
      designer: 'Julias Needle Designs',
      item: 'September',
      hoopSize: ['6x10'],
      metaTags: ['month','word','fall','september'], 
      holiday: '',
      category: '',
      season: 'fall',
      colectionName: 'Flourish Months',
      single: false,
      alphabet: false,
      applique: false,
      zipFile: 'FlourishMonthsOfTheYear'
    },
    {
      id: 3,
      image: '800FlourishMonths-December.jpg',
      designer: 'Julias Needle Designs',
      item: 'December',
      hoopSize: ['6x10'],
      metaTags: ['month','word','fall','December'], 
      holiday: 'Christmas',
      category: '',
      season: 'fall',
      colectionName: 'Flourish Months',
      single: false,
      alphabet: false,
      applique: false,
      zipFile: 'FlourishMonthsOfTheYear'
    },
    {
      id: 4,
      image: '800FlourishMonths-November.jpg',
      designer: 'Julias Needle Designs',
      item: 'November',
      hoopSize: ['6x10'],
      metaTags: ['month','word','fall','November'], 
      holiday: 'Thanksgiving',
      category: '',
      season: 'fall',
      colectionName: 'Flourish Months',
      single: false,
      alphabet: false,
      applique: false,
      zipFile: 'FlourishMonthsOfTheYear'
    },
    {
      id: 5,
      image: 'CCFREEBIE-HALLOWEENBEAR.jpg',
      designer: 'Julias Needle Designs',
      item: 'Lion Witch',
      hoopSize: ['4x4'],
      metaTags: ['lion','bear','fall','halloween','witch','children'], 
      holiday: 'Halloween',
      category: '',
      season: 'fall',
      colectionName: '',
      single: true,
      alphabet: false,
      applique: false,
      zipFile: 'FREEBIE-HALLOWEENBEAR'
    },
    {
      id: 6,
      image: 'CCLemonadeMasonJar.jpg',
      designer: 'Julias Needle Designs',
      item: 'Mason Jar',
      hoopSize: ['5x7','6x10'],
      metaTags: ['food','mason jar','lemon','summer','drink'], 
      holiday: '',
      category: '',
      season: 'summer',
      colectionName: '',
      single: true,
      alphabet: false,
      applique: false,
      zipFile: 'FREE-JND-LemonadeMasonJar'
    },
    {
      id: 7,
      image: 'CCJungleFriends-Bull.bmp',
      designer: 'Julias Needle Designs',
      item: 'Bull',
      hoopSize: ['4x4','5x7'],
      metaTags: ['animal','bull','swirly','children'], 
      holiday: '',
      category: '',
      season: '',
      colectionName: 'Jungle Friends',
      single: false,
      alphabet: false,
      applique: false,
      zipFile: 'SwirlyJungleFriends'
    },
    {
      id: 8,
      image: 'CCJungleFriends-Flamingo.bmp',
      designer: 'Julias Needle Designs',
      item: 'Flamingo',
      hoopSize: ['4x4','5x7'],
      metaTags: ['bird','flamingo','swirly','children'], 
      holiday: '',
      category: '',
      season: '',
      colectionName: 'Jungle Friends',
      single: false,
      alphabet: false,
      applique: false,
      zipFile: 'SwirlyJungleFriends'
    },
    {
      id: 9,
      image: 'CCApp CrescentWrench.jpg',
      designer: 'Julias Needle Designs',
      item: 'wrench',
      hoopSize: ['4x4'],
      metaTags: ['tool','wrench','children','applique','crescent wrench'], 
      holiday: '',
      category: '',
      season: '',
      colectionName: 'Funny Tools 2',
      single: false,
      alphabet: false,
      applique: true,
      zipFile: 'FUNNYTOOLS2'
    },
    {
      id: 10,
      image: 'CCApp File.jpg',
      designer: 'Julias Needle Designs',
      item: 'wrench',
      hoopSize: ['4x4'],
      metaTags: ['tool','file','children','applique'], 
      holiday: '',
      category: '',
      season: '',
      colectionName: 'Funny Tools 2',
      single: false,
      alphabet: false,
      applique: true,
      zipFile: 'FUNNYTOOLS2'
    }
   
  ];
  